name: utf-7
description: Encodes/decodes the "mail-safe transformation format of unicode" utf-7, rfc 2152
version: 0.0.1
# homepage: https://www.example.com
author: Michael Spiss <michaelspiss.dev@mailbox.org>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
