name: Dart CI

on:
  push:
  pull_request:
  schedule:
  - cron: 0 0 1 * *

jobs:
  build_stable:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
      
  build_dev:

    runs-on: ubuntu-latest
    
    container:
      image:  google/dart:dev
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
